title: "Felix's Digital Garden"
description: "Thoughts, code, and everything in between"
url: "https://felixtp.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - vendor/ruby/
  - .git/
  - .gitignore
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - _drafts/
  - "*.log"
  - "*.tmp"
  - "*.bak"