title: Felix
description: Personal blog
url: "https://felixtp.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - vendor/ruby/
  - .git/
  - .gitignore
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - _drafts/
  - "*.log"
  - "*.tmp"
  - "*.bak"