title: "Felix's Digital Garden"
description: "where ideas grow slowly and bugs are features"
url: "https://felixtp.github.io"
baseurl: ""
author: "Felix"

markdown: kramdown
highlighter: rouge
future: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - vendor/ruby/
  - .git/
  - .gitignore
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - _drafts/
  - "*.log"
  - "*.tmp"
  - "*.bak"