navigation:
  - title: "Home"
    url: "/"
    order: 1
  - title: "Blog"
    url: "/blog/"
    order: 2
  - title: "About"
    url: "/about/"
    order: 3
  - title: "Projects"
    url: "/projects/"
    order: 4
  - title: "Contact"
    url: "/contact/"
    order: 5

social:
  - platform: "github"
    url: "https://github.com/felixtp"
    icon: "🐙"
  - platform: "linkedin"
    url: "#"
    icon: "💼"
  - platform: "twitter"
    url: "#"
    icon: "🐦"
  - platform: "email"
    url: "mailto:felix@example.com"
    icon: "📧"

footer_links:
  - title: "RSS Feed"
    url: "/feed.xml"
    icon: "📡"
  - title: "Sitemap"
    url: "/sitemap.xml"
    icon: "🗺️"
  - title: "Privacy Policy"
    url: "/privacy/"
    icon: "🔒"

features:
  search: true
  dark_mode: true
  reading_progress: true
  social_sharing: true
  newsletter: true
  comments: false
